### ISSUE TITLE
'id' not recognized as valid property

### ISSUE THREAD

**Issue by lucasheim** [ui5-next/types#11]
I'm trying to create a Typescript App using typings from this repo and babel plugin from ui5-next/babel-plugin-ui5-next. I got the base code from ui5-next/ui5g ui5wt example. I'm using this snippet to create the App:

```
public createContent(controller: Controller) {
    this.addStyleClass((controller.getOwnerComponent() as any).getContentDensityClass());
    return new Application({ id: "app" });
  }
```

But `id` is not being recognized as a valid property:
![image](https://user-images.githubusercontent.com/13325346/66039911-8669b480-e4ec-11e9-8e2d-9e412d6adbce.png)

This is true for any other control, the same error happens when I try:
`new Table({id: "lala"});`

`id` seems to be missing as one of the base properties for every control.

**Comment by Soontao** [comment]
You're right. 
JSDoc not include the `id` field, so that generated type not have that.

**Comment by Soontao** [comment]
* Hard code to enhance the `Control` class property - id
