### ISSUE TITLE
Cannot use methods with notation as 'sap.ui.getCore().method()'

### ISSUE THREAD

**Issue by lucasheim** [ui5-next/types#12]
I'm using this snippet as my app's index.tsx, and trying to boot UI5 like this:

```typescript
import Shell from "sap/m/Shell";
import ComponentContainer from "sap/ui/core/ComponentContainer";
import Component from "./Component";

sap.ui.getCore().boot();

const container = new Shell({ app: new ComponentContainer({ component: new Component() }) });

container.placeAt("content");
```

But I get an error:

![image](https://user-images.githubusercontent.com/13325346/66040172-2f181400-e4ed-11e9-98c4-8feb489d0ea6.png)

This happens when trying to call anything with syntax as `sap.`

**Comment by Soontao** [comment]
@lucasheim 
Maybe you need [this](https://www.npmjs.com/package/@types/openui5) old type definition module
