### ISSUE TITLE
Control props should be optional

### ISSUE THREAD

**Issue by lucasheim** [ui5-next/types#2]
I'm trying to create a Typescript project using these type definitions, but I'm getting an error when trying to specify just a few of the properties:

![image](https://user-images.githubusercontent.com/13325346/65960068-f9f6bd80-e429-11e9-9d19-cfb4476b77e1.png)
![image](https://user-images.githubusercontent.com/13325346/65960083-02e78f00-e42a-11e9-8558-134394b190a6.png)

The props should be optional in the type definition to avoid user having to specify all of them when we only need some of them, as most have default values.

![image](https://user-images.githubusercontent.com/13325346/65960121-1dba0380-e42a-11e9-97b2-df4c35b124a7.png)

**Comment by Soontao** [comment]
Got it, let me check that.

**Comment by Soontao** [comment]
Now, in the JSX props definition: 

* events
* properties
* associations
* aggregations

will be optional.

Available in the next version (maybe v1.3.4)

![image](https://user-images.githubusercontent.com/10473459/65961159-93ed5300-e488-11e9-8e26-891d7c9a5ddf.png)

**Comment by Soontao** [comment]
@lucasheim 
Please try version 1.4.0. It should work now.
