### ISSUE TITLE
Member 'props' implicitly has an 'any' type. (ElementAttributesProperty)

### ISSUE THREAD

**Issue by lucasheim** [ui5-next/types#7]
Props property in JSX.ElementAttributesProperty implicitly has an 'any' type.

![image](https://user-images.githubusercontent.com/13325346/66038772-6dabcf80-e4e9-11e9-8459-66ff1dd211ab.png)

**Comment by Soontao** [comment]
Yes, it should be `any`. This declaration means that the property which named `props` of a class is the the type of jsx props.

**Comment by lucasheim** [comment]
Ok, I can do that.
